name: TorchEnv
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas-profiling
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - openpyxl
  - networkx
  - streamlit
  - openai
  - dataclasses
  - graphviz
  - boto3
  - flask
  - pymysql
  - ffmpeg-python
  - pip
  - pip:
    - streamlit-pandas-profiling
    - pinecone-client
    - streamlit-audiorecorder
    - openai-whisper
    - librosa
    - streamlit-chat
    - langchain 
    - pexpect
    - audio-recorder-streamlit
    - tiktoken
    - tabulate
    - sweetviz
    - transformers
    - accelerate
    - einops 
    - huggingface_hub
    - streamlit-agraph
